company_names:
  'CDR.WA': 'CD Projekt'
  'PLW.WA': 'PlayWay'
  'TEN.WA': '11 bit studios'
  'BLO.WA': 'Bloober Team'
  'CIG.WA': 'CI Games'
  'PKO.WA': 'PKO Bank Polski'
  'PEO.WA': 'Bank Pekao'
  'ING.WA': 'ING Bank Śląski'
  'MBK.WA': 'mBank'
  'ALR.WA': 'Alior Bank'
  'PKN.WA': 'PKN Orlen'
  'TPE.WA': 'Tauron Polska Energia'
  'ENA.WA': 'Enea'
  'PGE.WA': 'Polska Grupa Energetyczna'
  'BMW.DE': 'Bayerische Motoren Werke AG'
  'SIE.DE': 'Siemens AG'
  'SAN.PA': 'Sanofi'
  'TTE.PA': 'TotalEnergies SE'
  'BP.L': 'BP p.l.c.'
  'HSBA.L': 'HSBC Holdings plc'
  'VOW3.DE': 'Volkswagen AG'
  'RNO.PA': 'Renault SA'
  'NG.L': 'National Grid plc'
  'AAPL': 'Apple Inc.'
  'MSFT': 'Microsoft Corporation'
  'TSLA': 'Tesla, Inc.'
  'GOOGL': 'Alphabet Inc.'
  'AMZN': 'Amazon.com, Inc.'
  'NKE': 'Nike, Inc.'
  'JPM': 'JPMorgan Chase & Co.'
  'XOM': 'Exxon Mobil Corporation'
  'PFE': 'Pfizer Inc.'
  '7203.T': 'Toyota Motor Corporation'
  '9984.T': 'SoftBank Group Corp.'
  '005930.KS': 'Samsung Electronics Co., Ltd.'
  '2330.TW': 'Taiwan Semiconductor Manufacturing Company Limited'
  'BABA': 'Alibaba Group Holding Limited'
  'JD': 'JD.com, Inc.'
  'INFY.NS': 'Infosys Limited'
  'RELIANCE.NS': 'Reliance Industries Limited'
  'TM': 'Toyota Motor Corporation (ADR)'
  'SONY': 'Sony Group Corporation'
  'TCTZF': 'Tencent Holdings Limited'
  'HDB': 'HDFC Bank Limited'