# Data settings
data:
  years: 3
  raw_data_path: data/stock_data.csv
  processed_data_path: data/processed_dataset.pt
  normalizers_path: data/normalizers.pkl
  # Tickery
  tickers_file: config/training_tickers.yaml

# Model settings
model:
  max_prediction_length: 90
  min_encoder_length: 50
  max_encoder_length: 365
  hidden_size: 256
  attention_head_size: 8
  dropout: 0.2
  learning_rate: 0.001
  lstm_layers: 4
  loss: QuantileLoss
  use_quantile_loss: true
  quantiles: [0.1, 0.5, 0.9]
  min_hidden_size: 64
  max_hidden_size: 256
  min_lstm_layers: 3
  max_lstm_layers: 4
  min_attention_head_size: 6
  max_attention_head_size: 12

# Training settings
training:
  max_epochs: 100
  batch_size: 32
  early_stopping_patience: 10
  optuna_trials: 5  # Number of trials for hyperparameter optimization
  reduce_lr_patience: 3
  reduce_lr_factor: 0.3

# Paths
paths:
  checkpoint_path: 'models/best_tft_checkpoint.pth'
  model_save_path: 'models/full_model.pth'