# Data settings
data:
  years: 3
  raw_data_path: data/stock_data.csv
  processed_data_path: data/processed_dataset.pt
  normalizers_path: data/normalizers.pkl
  tickers_file: config/training_tickers.yaml
  company_names_file: config/company_names.yaml

# Model settings
model:
  max_prediction_length: 90
  min_encoder_length: 50         # mniejsze okno wejściowe
  max_encoder_length: 180        # mniejsze historyczne dane
  hidden_size: 128               # z 256 → 128
  attention_head_size: 4         # z 8 → 4
  dropout: 0.3                   # mniejszy dropout dla stabilności
  learning_rate: 0.001
  lstm_layers: 2                 # z 4 → 2 (oszczędność pamięci)
  loss: QuantileLoss
  use_quantile_loss: true
  quantiles: [0.1, 0.5, 0.9]
  # Hyperparameter ranges for Optuna
  min_hidden_size: 64
  max_hidden_size: 128
  min_lstm_layers: 1
  max_lstm_layers: 2
  min_attention_head_size: 2
  max_attention_head_size: 4

# Training settings
training:
  max_epochs: 100
  batch_size: 64
  early_stopping_patience: 10
  optuna_trials: 5              # Number of trials for hyperparameter optimization
  reduce_lr_patience: 3
  reduce_lr_factor: 0.6

# Paths
paths:
  checkpoint_path: 'models/best_tft_checkpoint.pth'
  model_save_path: 'models/full_model.pth'
