tickers:
  poland:
    - ticker: 'CDR.WA'
      name: 'CD Projekt'
    - ticker: 'PLW.WA'
      name: 'PlayWay'
    - ticker: 'TEN.WA'
      name: '11 bit studios'
    - ticker: 'BLO.WA'
      name: 'Bloober Team'
    - ticker: 'CIG.WA'
      name: 'CI Games'
    - ticker: 'PKO.WA'
      name: 'PKO Bank Polski'
    - ticker: 'PEO.WA'
      name: 'Bank Pekao'
    - ticker: 'ING.WA'
      name: 'ING Bank Śląski'
    - ticker: 'MBK.WA'
      name: 'mBank'
    - ticker: 'ALR.WA'
      name: 'Alior Bank'
    - ticker: 'PKN.WA'
      name: 'PKN Orlen'
    - ticker: 'TPE.WA'
      name: 'Tauron Polska Energia'
    - ticker: 'ENA.WA'
      name: 'Enea'
    - ticker: 'PGE.WA'
      name: 'Polska Grupa Energetyczna'
    - ticker: 'KGH.WA'
      name: 'KGHM Polska Miedź'
    - ticker: 'LPP.WA'
      name: 'LPP'
    - ticker: 'JSW.WA'
      name: 'Jastrzębska Spółka Węglowa'
    - ticker: 'DNP.WA'
      name: 'Dino Polska'
    - ticker: 'CPS.WA'
      name: 'Cyfrowy Polsat'
    - ticker: 'PZU.WA'
      name: 'PZU'
    - ticker: 'KRK.WA'
      name: 'Kruk'
    - ticker: 'ACP.WA'
      name: 'Asseco Poland'
  europe:
    - ticker: 'BMW.DE'
      name: 'Bayerische Motoren Werke AG'
    - ticker: 'SIE.DE'
      name: 'Siemens AG'
    - ticker: 'SAN.PA'
      name: 'Sanofi'
    - ticker: 'TTE.PA'
      name: 'TotalEnergies SE'
    - ticker: 'BP.L'
      name: 'BP p.l.c.'
    - ticker: 'HSBA.L'
      name: 'HSBC Holdings plc'
    - ticker: 'VOW3.DE'
      name: 'Volkswagen AG'
    - ticker: 'RNO.PA'
      name: 'Renault SA'
    - ticker: 'NG.L'
      name: 'National Grid plc'
    - ticker: 'DB1.DE'
      name: 'Deutsche Börse'
    - ticker: 'AIR.PA'
      name: 'Airbus'
    - ticker: 'BAS.DE'
      name: 'BASF'
    - ticker: 'SAP.DE'
      name: 'SAP'
    - ticker: 'BNP.PA'
      name: 'BNP Paribas'
    - ticker: 'AZN.L'
      name: 'AstraZeneca'
    - ticker: 'NOVN.SW'
      name: 'Novartis'
    - ticker: 'ROG.SW'
      name: 'Roche'
    - ticker: 'NESN.SW'
      name: 'Nestlé'
    - ticker: 'DTE.DE'
      name: 'Deutsche Telekom'
  usa:
    - ticker: 'AAPL'
      name: 'Apple Inc.'
    - ticker: 'MSFT'
      name: 'Microsoft Corporation'
    - ticker: 'TSLA'
      name: 'Tesla, Inc.'
    - ticker: 'GOOGL'
      name: 'Alphabet Inc.'
    - ticker: 'AMZN'
      name: 'Amazon.com, Inc.'
    - ticker: 'NKE'
      name: 'Nike, Inc.'
    - ticker: 'JPM'
      name: 'JPMorgan Chase & Co.'
    - ticker: 'XOM'
      name: 'Exxon Mobil Corporation'
    - ticker: 'PFE'
      name: 'Pfizer Inc.'
    - ticker: 'NVDA'
      name: 'NVIDIA'
    - ticker: 'META'
      name: 'Meta Platforms'
    - ticker: 'V'
      name: 'Visa'
    - ticker: 'MA'
      name: 'Mastercard'
    - ticker: 'DIS'
      name: 'Walt Disney'
    - ticker: 'NFLX'
      name: 'Netflix'
    - ticker: 'INTC'
      name: 'Intel'
    - ticker: 'AMD'
      name: 'Advanced Micro Devices'
    - ticker: 'CSCO'
      name: 'Cisco Systems'
    - ticker: 'KO'
      name: 'Coca-Cola'
    - ticker: 'PG'
      name: 'Procter & Gamble'
    - ticker: 'WFC'
      name: 'Wells Fargo'
  global:
    - ticker: '7203.T'
      name: 'Toyota Motor Corporation'
    - ticker: '9984.T'
      name: 'SoftBank Group Corp.'
    - ticker: '005930.KS'
      name: 'Samsung Electronics Co., Ltd.'
    - ticker: '2330.TW'
      name: 'Taiwan Semiconductor Manufacturing Company Limited'
    - ticker: 'BABA'
      name: 'Alibaba Group Holding Limited'
    - ticker: 'JD'
      name: 'JD.com, Inc.'
    - ticker: 'INFY.NS'
      name: 'Infosys Limited'
    - ticker: 'RELIANCE.NS'
      name: 'Reliance Industries Limited'
    - ticker: 'TM'
      name: 'Toyota Motor Corporation (ADR)'
    - ticker: 'SONY'
      name: 'Sony Group Corporation'
    - ticker: 'TCTZF'
      name: 'Tencent Holdings Limited'
    - ticker: 'HDB'
      name: 'HDFC Bank Limited'
    - ticker: 'BRK-B'
      name: 'Berkshire Hathaway'
    - ticker: 'WMT'
      name: 'Walmart'
    - ticker: '005380.KS'
      name: 'Hyundai Motor'
    - ticker: '1211.HK'
      name: 'BYD Company'
    - ticker: '8035.T'
      name: 'Tokyo Electron'
    - ticker: '3690.HK'
      name: 'Meituan'
    - ticker: '0700.HK'
      name: 'Tencent Holdings'
    - ticker: 'NTTYY'
      name: 'Nippon Telegraph and Telephone'
    - ticker: 'TCS.NS'
      name: 'Tata Consultancy Services'