tickers:
  poland:
    - 'CDR.WA'    # CD Projekt
    - 'PLW.WA'    # PlayWay
    - 'TEN.WA'    # 11 bit studios
    - 'BLO.WA'    # Bloober Team
    - 'CIG.WA'    # CI Games
    - 'PKO.WA'    # PKO BP
    - 'PEO.WA'    # Bank Pekao
    - 'ING.WA'    # ING Bank Śląski
    - 'MBK.WA'    # mBank
    - 'ALR.WA'    # Alior Bank
    - 'PKN.WA'    # Orlen
    - 'TPE.WA'    # Tauron
    - 'ENA.WA'    # Enea
    - 'PGE.WA'    # PGE
  europe:
    - 'BMW.DE'    # BMW
    - 'SIE.DE'    # Siemens
    - 'SAN.PA'    # Sanofi
    - 'TTE.PA'    # TotalEnergies
    - 'BP.L'      # BP
    - 'HSBA.L'    # HSBC
    - 'VOW3.DE'   # Volkswagen
    - 'RNO.PA'    # Renault
    - 'NG.L'      # National Grid
  usa:
    - 'AAPL'      # Apple
    - 'MSFT'      # Microsoft
    - 'TSLA'      # Tesla
    - 'GOOGL'     # Alphabet
    - 'AMZN'      # Amazon
    - 'NKE'       # Nike
    - 'JPM'       # JPMorgan Chase
    - 'XOM'       # Exxon Mobil
    - 'PFE'       # Pfizer
  global:
    - '7203.T'    # Toyota (Japonia)
    - '9984.T'    # SoftBank (Japonia)
    - '005930.KS' # Samsung (Korea Południowa)
    - '2330.TW'   # TSMC (Tajwan)
    - 'BABA'      # Alibaba (Chiny)
    - 'JD'        # JD.com (Chiny)
    - 'INFY.NS'   # Infosys (Indie)
    - 'RELIANCE.NS' # Reliance Industries (Indie)
    - 'TM'        # Toyota (USA)
    - 'SONY'      # Sony (Japonia)
    - 'TCTZF'     # Tencent (Chiny)
    - 'HDB'       # HDFC Bank (Indie)