tickers:
  poland:
    - 'CDR.WA'    # CD Projekt
    - 'PLW.WA'    # PlayWay
    - 'TEN.WA'    # 11 bit studios
    - 'BLO.WA'    # Bloober Team
    - 'CIG.WA'    # CI Games
    - 'PKO.WA'    # PKO BP
    - 'PEO.WA'    # Bank Pekao
    - 'ING.WA'    # ING Bank Śląski
    - 'MBK.WA'    # mBank
    - 'ALR.WA'    # Alior Bank
    - 'PKN.WA'    # Orlen
    - 'TPE.WA'    # Tauron
    - 'ENA.WA'    # Enea
    - 'PGE.WA'    # PGE
    - 'KGH.WA'    # KGHM Polska Miedź
    - 'LPP.WA'    # LPP
    - 'JSW.WA'    # Jastrzębska Spółka Węglowa
    - 'DNP.WA'    # Dino Polska
    - 'CPS.WA'    # Cyfrowy Polsat
    - 'PZU.WA'    # PZU
    - 'KRK.WA'    # Kruk
    - 'ACP.WA'    # Asseco Poland
  europe:
    - 'BMW.DE'    # BMW
    - 'SIE.DE'    # Siemens
    - 'SAN.PA'    # Sanofi
    - 'TTE.PA'    # TotalEnergies
    - 'BP.L'      # BP
    - 'HSBA.L'    # HSBC
    - 'VOW3.DE'   # Volkswagen
    - 'RNO.PA'    # Renault
    - 'NG.L'      # National Grid
    - 'DB1.DE'    # Deutsche Börse
    - 'AIR.PA'    # Airbus
    - 'BAS.DE'    # BASF
    - 'SAP.DE'    # SAP
    - 'BNP.PA'    # BNP Paribas
    - 'AZN.L'     # AstraZeneca
    - 'NOVN.SW'   # Novartis
    - 'ROG.SW'    # Roche
    - 'NESN.SW'   # Nestlé
    - 'DTE.DE'    # Deutsche Telekom
  usa:
    - 'AAPL'      # Apple
    - 'MSFT'      # Microsoft
    - 'TSLA'      # Tesla
    - 'GOOGL'     # Alphabet
    - 'AMZN'      # Amazon
    - 'NKE'       # Nike
    - 'JPM'       # JPMorgan Chase
    - 'XOM'       # Exxon Mobil
    - 'PFE'       # Pfizer
    - 'NVDA'      # NVIDIA
    - 'META'      # Meta Platforms
    - 'V'         # Visa
    - 'MA'        # Mastercard
    - 'DIS'       # Walt Disney
    - 'NFLX'      # Netflix
    - 'INTC'      # Intel
    - 'AMD'       # Advanced Micro Devices
    - 'CSCO'      # Cisco Systems
    - 'KO'        # Coca-Cola
    - 'PG'        # Procter & Gamble
    - 'WFC'       # Wells Fargo
  global:
    - '7203.T'    # Toyota (Japonia)
    - '9984.T'    # SoftBank (Japonia)
    - '005930.KS' # Samsung (Korea Południowa)
    - '2330.TW'   # TSMC (Tajwan)
    - 'BABA'      # Alibaba (Chiny)
    - 'JD'        # JD.com (Chiny)
    - 'INFY.NS'   # Infosys (Indie)
    - 'RELIANCE.NS' # Reliance Industries (Indie)
    - 'TM'        # Toyota (USA)
    - 'SONY'      # Sony (Japonia)
    - 'TCTZF'     # Tencent (Chiny)
    - 'HDB'       # HDFC Bank (Indie)
    - 'BRK-B'     # Berkshire Hathaway
    - 'WMT'       # Walmart
    - '005380.KS' # Hyundai Motor (Korea Południowa)
    - '1211.HK'   # BYD Company (Chiny)
    - '8035.T'    # Tokyo Electron (Japonia)
    - '3690.HK'   # Meituan (Chiny)
    - '0700.HK'   # Tencent Holdings (Hong Kong)
    - 'NTTYY'     # Nippon Telegraph and Telephone (Japonia)
    - 'TCS.NS'    # Tata Consultancy Services (Indie)